// Sample data copied from the Lovable design. Front end only — this is
// replaced by real API calls in src/lib/api.ts once the backend is merged.

import type { Client, ClientClaim, InsurerSummary } from "./types";

export const CLIENTS: Client[] = [
  {
    id: "CLT-001",
    name: "Kigali Steel Industries Ltd",
    type: "Corporate",
    sector: "Manufacturing",
    activePolicies: 4,
    kyc: true,
    policiesOk: true,
    claimsOk: false,
    correspondenceOk: true,
    docsFiled: 3,
    docsTotal: 4,
    nonCompliant: false,
    manager: "Jean-Paul Habimana",
    documents: [
      { name: "Certificate of Incorporation", filed: true, status: "ok" },
      { name: "Trading Licence", filed: true, expiry: "12 Oct 2026", status: "soon" },
      { name: "Tax Clearance (RRA)", filed: true, expiry: "31 Mar 2027", status: "ok" },
      { name: "Beneficial Ownership Register", filed: false },
    ],
    policies: [
      {
        id: "POL-2025-412",
        classOfInsurance: "Industrial All Risk",
        insurer: "SONARWA",
        sumInsured: 1800000000,
        premium: 31200000,
        start: "21 Sep 2025",
        renewal: "21 Sep 2026",
        status: "In Renewal",
      },
      {
        id: "POL-2025-418",
        classOfInsurance: "Marine Cargo",
        insurer: "SONARWA",
        sumInsured: 420000000,
        premium: 7400000,
        start: "01 Feb 2026",
        renewal: "01 Feb 2027",
        status: "Active",
      },
    ],
    correspondence: [
      { date: "18 Sep 2026", subject: "Renewal options presented", channel: "Email" },
      { date: "02 Sep 2026", subject: "FNOL acknowledgement CLM-2025-089", channel: "Email" },
    ],
  },
  {
    id: "CLT-002",
    name: "Rwanda Energy Group",
    type: "State Enterprise",
    sector: "Energy",
    activePolicies: 9,
    kyc: false,
    policiesOk: true,
    claimsOk: true,
    correspondenceOk: false,
    docsFiled: 2,
    docsTotal: 4,
    nonCompliant: false,
    manager: "Marie Claire Uwimana",
    documents: [
      { name: "Establishment Instrument", filed: true, status: "ok" },
      { name: "Board Resolution", filed: true, status: "ok" },
      { name: "Tax Clearance (RRA)", filed: false },
      { name: "Authorised Signatory List", filed: false },
    ],
    policies: [
      {
        id: "POL-2025-299",
        classOfInsurance: "Motor Fleet",
        insurer: "RADIANT",
        sumInsured: 960000000,
        premium: 8700000,
        start: "20 Oct 2025",
        renewal: "20 Oct 2026",
        status: "In Renewal",
      },
      {
        id: "POL-2025-341",
        classOfInsurance: "Public Liability",
        insurer: "CORAR",
        sumInsured: 500000000,
        premium: 3600000,
        start: "09 Nov 2025",
        renewal: "09 Nov 2026",
        status: "Active",
      },
    ],
    correspondence: [{ date: "11 Sep 2026", subject: "KYC document request", channel: "Letter" }],
  },
  {
    id: "CLT-003",
    name: "Bralirwa PLC",
    type: "Corporate",
    sector: "FMCG",
    activePolicies: 3,
    kyc: true,
    policiesOk: true,
    claimsOk: true,
    correspondenceOk: true,
    docsFiled: 4,
    docsTotal: 4,
    nonCompliant: false,
    manager: "Eric Niyonzima",
    documents: [
      { name: "Certificate of Incorporation", filed: true, status: "ok" },
      { name: "Trading Licence", filed: true, expiry: "30 Jun 2027", status: "ok" },
      { name: "Tax Clearance (RRA)", filed: true, expiry: "31 Dec 2026", status: "ok" },
      { name: "Beneficial Ownership Register", filed: true, status: "ok" },
    ],
    policies: [
      {
        id: "POL-2025-188",
        classOfInsurance: "Property All Risk",
        insurer: "UAP",
        sumInsured: 1100000000,
        premium: 14300000,
        start: "05 Dec 2025",
        renewal: "05 Dec 2026",
        status: "Active",
      },
    ],
    correspondence: [{ date: "14 Sep 2026", subject: "Assessment visit scheduled", channel: "Email" }],
  },
  {
    id: "CLT-004",
    name: "Bank of Kigali",
    type: "Financial Institution",
    sector: "Banking",
    activePolicies: 6,
    kyc: false,
    policiesOk: false,
    claimsOk: true,
    correspondenceOk: true,
    docsFiled: 2,
    docsTotal: 4,
    nonCompliant: true,
    manager: "Isabelle Mukamana",
    documents: [
      { name: "Certificate of Incorporation", filed: true, status: "ok" },
      { name: "BNR Operating Licence", filed: true, expiry: "01 Aug 2026", status: "expired" },
      { name: "Tax Clearance (RRA)", filed: false },
      { name: "Authorised Signatory List", filed: false },
    ],
    policies: [
      {
        id: "POL-2025-107",
        classOfInsurance: "Professional Indemnity",
        insurer: "SORAS",
        sumInsured: 2400000000,
        premium: 22100000,
        start: "03 Oct 2025",
        renewal: "03 Oct 2026",
        status: "In Renewal",
      },
    ],
    correspondence: [{ date: "09 Sep 2026", subject: "Licence renewal follow-up", channel: "Call" }],
  },
  {
    id: "CLT-005",
    name: "Horizon Logistics Rwanda",
    type: "SME",
    sector: "Transport",
    activePolicies: 2,
    kyc: true,
    policiesOk: true,
    claimsOk: true,
    correspondenceOk: false,
    docsFiled: 3,
    docsTotal: 4,
    nonCompliant: false,
    manager: "Eric Niyonzima",
    documents: [
      { name: "Certificate of Incorporation", filed: true, status: "ok" },
      { name: "Trading Licence", filed: true, expiry: "05 Oct 2026", status: "soon" },
      { name: "Tax Clearance (RRA)", filed: true, expiry: "28 Feb 2027", status: "ok" },
      { name: "Beneficial Ownership Register", filed: false },
    ],
    policies: [
      {
        id: "POL-2025-455",
        classOfInsurance: "Goods in Transit",
        insurer: "RADIANT",
        sumInsured: 260000000,
        premium: 4100000,
        start: "15 Jan 2026",
        renewal: "15 Jan 2027",
        status: "Active",
      },
    ],
    correspondence: [{ date: "01 Sep 2026", subject: "Fleet schedule update", channel: "Email" }],
  },
];

// Only the claim fields the client profile needs.
export const CLIENT_CLAIMS: ClientClaim[] = [
  { id: "CLM-2025-089", client: "Kigali Steel Industries Ltd", classOfInsurance: "Industrial All Risk", amount: 42000000, step: 2, sla: "breached" },
  { id: "CLM-2025-078", client: "Rwanda Energy Group", classOfInsurance: "Motor Fleet", amount: 4200000, step: 5, sla: "breached" },
  { id: "CLM-2025-071", client: "Bralirwa PLC", classOfInsurance: "Property All Risk", amount: 8500000, step: 3, sla: "approaching" },
  { id: "CLM-2025-064", client: "Bank of Kigali", classOfInsurance: "Professional Indemnity", amount: 1200000, step: 1, sla: "ontrack" },
  { id: "CLM-2025-061", client: "Rwanda Energy Group", classOfInsurance: "Public Liability", amount: 6750000, step: 5, sla: "approaching" },
  { id: "CLM-2025-057", client: "Kigali Steel Industries Ltd", classOfInsurance: "Marine Cargo", amount: 19400000, step: 4, sla: "ontrack" },
  { id: "CLM-2025-052", client: "Bralirwa PLC", classOfInsurance: "Group Personal Accident", amount: 480000, step: 6, sla: "ontrack" },
  { id: "CLM-2025-046", client: "Bank of Kigali", classOfInsurance: "Money Insurance", amount: 15300000, step: 5, sla: "approaching" },
];

export const POLICIES_BY_INSURER: InsurerSummary[] = [
  { insurer: "SONARWA", policies: 12, premium: 64 },
  { insurer: "RADIANT", policies: 9, premium: 38 },
  { insurer: "UAP", policies: 7, premium: 31 },
  { insurer: "SORAS", policies: 6, premium: 42 },
  { insurer: "CORAR", policies: 4, premium: 17 },
];
